imports:
  - resource: facet_mapping_regions.yml
  - resource: facet_mapping_types.yml
  - resource: facet_mapping_themes.yml
  - resource: facet_mapping_facilities.yml
  - resource: features.yml
debug: false
bootstrap: []
uitid:
  consumer:
    key: ***
    secret: ***
  base_url: http://www.uitid.be/uitid/rest/
consumerExecutionDelay: 0
amqp:
  host: 127.0.0.1
  port: 5672
  vhost: udb3-vagrant
  user: vagrant
  password: vagrant
  consumer_tag: udb3-vagrant
  consumers:
    udb3-core:
      exchange: udb3.vagrant.x.domain-events
      queue: search.vagrant.q.udb3-domain-events
elasticsearch:
  host: http://elasticsearch.dev:9200
  aggregation_size: 100
  udb3_core_index:
    prefix: udb3_core_v
    read_alias: udb3_core_read
    write_alias: udb3_core_write
    reindexation:
      from: udb3_core_read
      scroll_ttl: '1m'
      scroll_size: 30
      bulk_threshold: 10
  geoshapes_index:
    prefix: geoshapes_v
    read_alias: geoshapes_read
    write_alias: geoshapes_write
    indexation:
      to: geoshapes_write
      path: '../geojson-data/elasticsearch'
      fileName: '*.json'
  organizer:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: organizer
  event:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: event
  place:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: place
  region_query:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: region_query
  offer:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: 'event,place'
  region:
    read_index: geoshapes_read
    write_index: geoshapes_write
    document_type: region
cors:
  origins:
    - http://udb-app.dev
    - http://localhost:9999
cache:
  redis:
    host: 127.0.0.1
    database: 1
  lifetime: 86400
