debug: false
bootstrap: []
consumerExecutionDelay: 0
amqp:
  host: 127.0.0.1
  port: 5672
  vhost: udb3-vagrant
  user: vagrant
  password: vagrant
  consumer_tag: udb3-vagrant
  consumers:
    udb3-core:
      exchange: udb3.vagrant.x.domain-events
      queue: search.vagrant.q.udb3-domain-events
elasticsearch:
  host: http://elasticsearch.dev:9200
  udb3_core_index:
    latest: udb3_core_v1
    previous: udb3_core_20161011000440
    read_alias: udb3_core_read
    write_alias: udb3_core_write
  organizer:
    read_index: udb3_core_read
    write_index: udb3_core_write
    document_type: organizer
cors:
  origins:
    - http://udb-app.dev
    - http://localhost:9999
