services:
  search:
    build: docker/php
    container_name: search.uitdatabank
    volumes:
      - .:/var/www/html:cached
      - ../geojson-data:/var/www/geojson-data:cached
    working_dir: /var/www/html
    ports:
      - "${FORWARD_PHP_PORT:-9000}:80"
    networks:
      uitdatabank-search:
        aliases:
          - search.uitdatabank.local
    healthcheck:
      test: curl http://127.0.0.1:80/
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: public.ecr.aws/y2o7k5u2/udb3/elasticsearch:5.3.3
    container_name: es.uitdatabank
    hostname: 'udb3-es'
    ports:
      - '9200:9200'
    volumes:
      - 'udb3-es:/elasticsearch/data'
    networks:
      uitdatabank-search:
        aliases:
          - elasticsearch.uitdatabank.local
    healthcheck:
      #test: 'curl --fail http://127.0.0.1:9200/_cluster/health?wait_for_status=green&timeout=1s'
      test: 'wget -o /dev/null -T 3 http://127.0.0.1:9200/_cluster/health'
      interval: 5s
      timeout: 4s

networks:
  uitdatabank-search:
    name: uitdatabank
    external: true

volumes:
  udb3-es:
    driver: local
