version: "3.5"

services:

  search:
    build: docker/php
    container_name: search.uitdatabank
    volumes:
      - .:/var/www/html:cached
      - ../geojson-data:/var/www/geojson-data:cached
    working_dir: /var/www/html
    ports:
      - "9000:80"
    networks:
      uitdatabank:
        aliases:
          - search.uitdatabank.dev

  elasticsearch:
    image: public.ecr.aws/y2o7k5u2/udb3/elasticsearch:5.3.3
    container_name: es.uitdatabank
    hostname: 'udb3-es'
    ports:
      - '9200:9200'
    volumes:
      - 'udb3-es:/elasticsearch/data'
    networks:
      uitdatabank:
        aliases:
            - elasticsearch.uitdatabank.dev

  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es8.uitdatabank
    hostname: 'udb3-es8'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - '9208:9200'
    volumes:
      - 'udb3-es8:/elasticsearch/data'
    networks:
      uitdatabank:
        aliases:
          - elasticsearch.uitdatabank.dev

networks:
  uitdatabank:
    driver: bridge

volumes:
  udb3-es:
    driver: local
  udb3-es8:
    driver: local