version: "3.5"

services:

  search:
    build: docker/php
    container_name: search.uitdatabank
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    command:
      - /bin/bash
      - -c
      - |
        php bin/app.php consume-udb3-api &
        php bin/app.php consume-udb3-cli &
        php bin/app.php consume-udb3-related &
        php -S 0.0.0.0:9000 -t web
    ports:
      - "9000:9000"
    networks:
      uitdatabank:
        aliases:
          - search.uitdatabank.dev

  elasticsearch:
    image: public.ecr.aws/y2o7k5u2/udb3/elasticsearch:5.3.3
    restart: always
    ports:
      - '9200:9200'
    expose:
      - '9200'
    networks:
      uitdatabank:
        aliases:
            - elasticsearch.uitdatabank.dev

networks:
  uitdatabank:
    driver: bridge

